### ISSUE TITLE
Not pushing code in github

### ISSUE THREAD

**Issue by hykuBipin** [cbkinase/StructyHub#1]
Hi ,
 I am hereby mentioning that this chrome extension unable to push my code commit from structy into my github repository. Could you please help me to fix it asap. Thanks.

**Comment by cbkinase** [comment]
Hi there, and thanks for checking out StructyHub. Everything is working on my end, so I'll recommend the following troubleshooting steps:

First, I would

1) Make sure you are using Chrome or a Chrome-based browser.
2) Ensure Chrome (or whatever Chrome-based browser you use) is fully up-to-date.

If you've done this, I would try

3) If there was a problem with authentication, uninstall and reinstall the extension.
4) If you ARE authenticated and it fails to synchronize with GitHub you can simply try refreshing the page and submit your response again. The second submission should work.

Please let me know if this resolves your problem. Otherwise, I might need more information such as the browser you are using, and (if you set one) the customized repository name.
